/* eslint-disable @typescript-eslint/no-explicit-any */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/man.glb --typescript 
*/

import { useGLTF } from '@react-three/drei';
import { BufferGeometry, Material, Mesh } from 'three';

interface ModelProps {
  [key: string]: any;
}

export function Model(props: ModelProps) {
  const { nodes, materials } = useGLTF('/man.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={(nodes.mesh_0 as unknown as Mesh).geometry as BufferGeometry} material={(nodes.mesh_0 as unknown as Mesh).material as Material | Material[] | undefined} />
    </group>
  )
}

useGLTF.preload('/man.glb')
